version: '3.8'

services:
  iris:
    build:
      context: .
    ports:
      - "3000:3000"  # IRIS frontend on localhost:3000
    depends_on:
      - tiny
    environment:
      - NEXT_PUBLIC_RERUM_GATEWAY=http://tiny:4000

  rerum:
    build:
      context: ./rerum_server_nodejs
    ports:
      - "3002:3002"  # Host 3002 → Container 3002  (- "HOST_PORT:CONTAINER_PORT")

    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/rerum

  tiny:
    build:
      context: ./TinyNode
    ports:
      - "4000:4000"
    env_file:
      - ./TinyNode/.env
    depends_on:
      - rerum

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
