name: CI

# Trigger the workflow on pushes and pull requests to main
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Node
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Run tests
      - name: Run tests
        run: yarn test:ci

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t my-iris-app:latest .

      # 6. Run Docker container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag my-iris-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-iris-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-iris-app:latest
