name: Build and Release


on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name : in
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  build:
    needs: release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Build web assets
        run: yarn build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Build Android
        if: matrix.platform == 'android'
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Android Artifact
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
